# Generated by Django 2.2.11 on 2020-03-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='condition',
        ),
    ]
